spring:
  cloud:
    gateway:
      default-filter:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader: Cookie
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**          
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bikes/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8056/auth/realms/tutorial-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8056/auth/realms/tutorial-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8056/auth/realms/tutorial-realm/protocol/openid-connect/token
        registration:
          client-name:
            provider: keycload
            client_id: tutorial-client
            client_secret: uONJwAMo8QsyOx3NbpGMCBCmxhiZz6Gd
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/tutorial-client"
