spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**          
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bikes/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8056/auth/realms/tutorial-realm/protocol/openid-connect/auth
            user-info-uri: http://localhost:8056/auth/realms/tutorial-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8056/auth/realms/tutorial-realm/protocol/openid-connect/token
        registration:
          tutorial-client:
            provider: keycloak
            client-id: tutorial-client
            client-secret: uONJwAMo8QsyOx3NbpGMCBCmxhiZz6Gd
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8055/login/oauth2/code/tutorial-client"

