spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**          
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bikes/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
