server:
  port: 8083
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/shiryu-devs/spring-microservices
          search-paths: config-data
  application:
    name: config-service
          
           