server:
  port: 8053
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/shiryu-devs/spring-microservices
          search-paths: config-data
  application:
    name: config-service
           